name: Validate Pull Requests

env:
  APP: rocket delivery
  APP_DIR: src
  AWS_REGION: us-west-2

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "**"
jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: yarn install

      - name: Run prettier
        run: yarn prettier:check

      - name: Run tests
        run: yarn test

      - name: Build
        run: CI=false yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs


